FROM node:9-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

RUN npm install npm@latest -g

COPY package*.json ./

#RUN npm install
# If you are building your code for production
RUN npm install --only=production

# Fix vulnerabilities
RUN npm audit fix

# Bundle app source
#COPY . .

EXPOSE 8000
CMD [ "npm", "start" ]
