FROM node:9-alpine

# Create app directory
WORKDIR /usr/src/app

RUN apk add --no-cache --virtual .gyp \
        git \
        python \
        make \
        g++

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

RUN npm install npm@latest -g

COPY package*.json ./

#RUN npm install

# Fix vulnerabilities
RUN npm audit fix

#RUN apk del .gyp

# If you are building your code for production
RUN npm install --only=production

# Bundle app source
#COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]

